
import { Translations, Language } from './types';

export const STORAGE_KEY = 'anon_log_messages';
export const LAST_READ_KEY = 'anon_log_last_read_mine';
export const MAX_MESSAGE_LENGTH = 1200;
export const MAX_TAG_LENGTH = 32;

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    system_name: 'ANONLOG 1.01 // 00s VIBE',
    footer: 'Secure // Anonymous // Persistent',
    search_label: 'SEARCH //',
    search_placeholder: 'KEYWORD OR TAG...',
    search_placeholder_short: 'SEARCH...',
    search_clear: '[CLEAR]',
    input_placeholder: 'ENTER MESSAGE...',
    chars_label: 'CHARS',
    new_entry_label: 'NEW ENTRY',
    publish_btn: 'PUBLISH',
    replying_to_prefix: 'Replying to #',
    cancel_btn: 'CANCEL',
    all_messages_tab: 'All Messages',
    my_dialogs_tab: 'My Dialogs',
    no_entries: 'NO ENTRIES FOUND',
    no_dialogs: 'NO DIALOGS ACTIVE',
    id_label: 'ID',
    you_label: 'YOU',
    time_label: 'TIME',
    reply_btn: 'Reply',
    copy_btn: 'Copy',
    quick_entry_label: 'QUICK ENTRY //',
    send_btn: 'SEND',
    theme_light: 'LIGHT',
    theme_dark: 'DARK',
    session_key_label: 'SESSION KEY',
    session_expl_text: 'This is a cryptographic snapshot of your identity. Clearing browser history will delete this snapshot and all associated messages.',
    add_tag_btn: 'ADD TAG',
    tags_placeholder: 'Enter tags, comma separated',
    sort_newest: 'NEWEST FIRST',
    sort_oldest: 'OLDEST FIRST',
    preloader_title: 'ANONLOG',
    preloader_subtitle: 'LOAD MESSAGES',
    next_msg_label: 'NEXT MESSAGE',
    admin_login_title: 'GOD MODE ACCESS',
    login_btn: 'ENTER SYSTEM',
    logout_btn: 'LOGOUT',
    block_btn: 'BLOCK USER',
    admin_badge: 'ADMIN',
  },
  ru: {
    system_name: 'АНОНЛОГ 1.01 // ВАЙБ НУЛЕВЫХ',
    footer: 'Безопасно // Анонимно // Надежно',
    search_label: 'ПОИСК //',
    search_placeholder: 'КЛЮЧЕВОЕ СЛОВО ИЛИ ТЕГ...',
    search_placeholder_short: 'ПОИСК...',
    search_clear: '[ОЧИСТИТЬ]',
    input_placeholder: 'ВВЕДИТЕ СООБЩЕНИЕ...',
    chars_label: 'СИМВ',
    new_entry_label: 'НОВАЯ ЗАПИСЬ',
    publish_btn: 'ОПУБЛИКОВАТЬ',
    replying_to_prefix: 'Ответ на #',
    cancel_btn: 'ОТМЕНА',
    all_messages_tab: 'Все сообщения',
    my_dialogs_tab: 'Мои диалоги',
    no_entries: 'ЗАПИСИ НЕ НАЙДЕНЫ',
    no_dialogs: 'НЕТ АКТИВНЫХ ДИАЛОГОВ',
    id_label: 'ID',
    you_label: 'ВЫ',
    time_label: 'ВРЕМЯ',
    reply_btn: 'Ответить',
    copy_btn: 'Копировать',
    quick_entry_label: 'БЫСТРЫЙ ВВОД //',
    send_btn: 'ОТПРАВИТЬ',
    theme_light: 'ДЕНЬ',
    theme_dark: 'НОЧЬ',
    session_key_label: 'КЛЮЧ СЕССИИ',
    session_expl_text: 'Это криптографический слепок Вашей личности. При очистке кеша браузера этот слепок, и все сообщения вкладки "Мои диалоги" - удалятся.',
    add_tag_btn: 'ДОБАВИТЬ ТЕГ',
    tags_placeholder: 'Введите теги, разделяя их запятой',
    sort_newest: 'СНАЧАЛА НОВЫЕ',
    sort_oldest: 'СНАЧАЛА СТАРЫЕ',
    preloader_title: 'АНОНЛОГ',
    preloader_subtitle: 'ЗАГРУЗКА СООБЩЕНИЙ',
    next_msg_label: 'СЛЕД. СООБЩЕНИЕ',
    admin_login_title: 'ДОСТУП К РЕЖИМУ БОГА',
    login_btn: 'ВОЙТИ В СИСТЕМУ',
    logout_btn: 'ВЫЙТИ',
    block_btn: 'ЗАБЛОКИРОВАТЬ',
    admin_badge: 'АДМИН',
  }
};