
import { Translations, Language } from './types';

export const STORAGE_KEY = 'anon_log_messages';
export const LAST_READ_KEY = 'anon_log_last_read_mine';
export const MAX_MESSAGE_LENGTH = 2000; // Increased for "Posts"
export const MAX_TITLE_LENGTH = 300; // New constant
export const MAX_TAG_LENGTH = 32;

export const PREDEFINED_TAGS = [
  'Киберпанк', 'Технологии', 'Кодинг', 'Дизайн', 'Крипта', 'ИИ',
  'Игры', 'Музыка', 'Кино', 'Мемы', 'Новости', 'Наука',
  'Космос', 'Ретро', 'Железо', 'Софт', 'Приватность', 'Безопасность',
  'Стартапы', 'Карьера', 'Жизнь', 'Мысли', 'Вопрос', 'Оффтоп'
];

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    system_name: 'RETROLOG // Y2K VIBE',
    footer: 'Decentralized // Persistent // Community',
    search_label: 'SEARCH //',
    search_placeholder: 'FIND TOPICS...',
    search_placeholder_short: 'SEARCH...',
    search_clear: '[CLR]',
    input_placeholder: 'WRITE SOMETHING...',
    title_placeholder: 'POST TITLE (OPTIONAL)...',
    chars_label: 'CHARS',
    new_entry_label: 'CREATE POST',
    publish_btn: 'POST',
    replying_to_prefix: 'RE: #',
    cancel_btn: 'CANCEL',
    all_messages_tab: 'FEED',
    my_dialogs_tab: 'NOTIFICATIONS',
    no_entries: 'NO SIGNAL DETECTED',
    no_dialogs: 'NO ACTIVITY',
    id_label: 'ID',
    you_label: 'YOU',
    time_label: 'TIME',
    reply_btn: 'Reply',
    copy_btn: 'Copy',
    quick_entry_label: 'QUICK POST //',
    send_btn: 'SEND',
    theme_light: 'LIGHT',
    theme_dark: 'DARK',
    session_key_label: 'IDENTITY',
    session_expl_text: 'Your digital signature. Log in with Google to persist your karma and identity across devices.',
    add_tag_btn: 'TAG',
    tags_placeholder: 'Tags (comma separated)',
    sort_newest: 'NEWEST',
    sort_oldest: 'OLDEST',
    sort_best: 'TOP RATED',
    sort_newest_short: 'NEW',
    sort_oldest_short: 'OLD',
    sort_best_short: 'TOP',
    popular_tags_label: 'COMMUNITIES',
    preloader_title: 'RETROLOG',
    preloader_subtitle: 'ESTABLISHING UPLINK',
    next_msg_label: 'NEXT',
    admin_login_title: 'ROOT ACCESS',
    login_btn: 'LOG IN',
    logout_btn: 'LOGOUT',
    block_btn: 'BAN',
    admin_badge: 'MOD',
    hide_panel_btn: 'HIDE',
    expand_panel_btn: 'EXPAND',
    menu_btn: 'MENU',
    close_btn: 'CLOSE',
    mobile_footer_text_1: 'Next-gen BBS system.',
    mobile_footer_text_2: '2025. Retrolog Network.',
    login_google: 'LOGIN WITH GOOGLE',
    guest_mode: 'GUEST ACCESS',
    // Auth Modal
    auth_title_login: 'SYSTEM LOGIN',
    auth_title_register: 'NEW REGISTRATION',
    auth_google_btn: 'CONTINUE WITH GOOGLE',
    auth_apple_btn: 'CONTINUE WITH APPLE',
    auth_or_divider: 'OR',
    auth_email_label: 'EMAIL',
    auth_password_label: 'PASSWORD',
    auth_username_label: 'USERNAME',
    auth_forgot_pass: 'FORGOT PASSWORD?',
    auth_has_account: 'ALREADY A USER?',
    auth_no_account: 'NEW TO RETROLOG?',
    auth_submit_login: 'AUTHENTICATE',
    auth_submit_register: 'REGISTER IDENTITY',
    auth_disclaimer: 'INITIATING SESSION SEQUENCE. BY PROCEEDING, YOU ACKNOWLEDGE COMPLIANCE WITH PROTOCOL 7 (TERMS) AND DATA RETENTION POLICY.',
    auth_switch_login: 'LOG IN',
    auth_switch_register: 'REGISTER',
    // Auth Errors
    error_generic: 'AUTHENTICATION FAILED',
    error_invalid_email: 'INVALID EMAIL FORMAT',
    error_user_disabled: 'USER ACCOUNT DISABLED',
    error_user_not_found: 'USER NOT FOUND',
    error_wrong_password: 'INVALID PASSWORD',
    error_email_already_in_use: 'EMAIL ALREADY REGISTERED',
    error_weak_password: 'PASSWORD TOO WEAK',
    error_missing_fields: 'ALL FIELDS REQUIRED',
    // Auth Success
    auth_reset_sent: 'RESET LINK SENT TO EMAIL',
    auth_verification_sent: 'VERIFICATION EMAIL SENT',
  },
  ru: {
    system_name: 'РЕТРОЛОГ // ВАЙБ НУЛЕВЫХ',
    footer: 'Децентрализация // Сообщество // Наследие',
    search_label: 'ПОИСК //',
    search_placeholder: 'НАЙТИ ТЕМУ...',
    search_placeholder_short: 'ПОИСК...',
    search_clear: '[СТЕРЕТЬ]',
    input_placeholder: 'Текст поста...',
    title_placeholder: 'ЗАГОЛОВОК (ОПЦИОНАЛЬНО)...',
    chars_label: 'СИМВ',
    new_entry_label: 'СОЗДАТЬ ПОСТ',
    publish_btn: 'ОПУБЛИКОВАТЬ',
    replying_to_prefix: 'Ответ на #',
    cancel_btn: 'ОТМЕНА',
    all_messages_tab: 'ЛЕНТА',
    my_dialogs_tab: 'УВЕДОМЛЕНИЯ',
    no_entries: 'СИГНАЛ НЕ ОБНАРУЖЕН',
    no_dialogs: 'НЕТ АКТИВНОСТИ',
    id_label: 'ID',
    you_label: 'ВЫ',
    time_label: 'ВРЕМЯ',
    reply_btn: 'Ответить',
    copy_btn: 'Копировать',
    quick_entry_label: 'БЫСТРЫЙ ПОСТ //',
    send_btn: 'ОТПРАВИТЬ',
    theme_light: 'ДЕНЬ',
    theme_dark: 'НОЧЬ',
    session_key_label: 'ЛИЧНОСТЬ',
    session_expl_text: 'Ваша цифровая подпись. Войдите через Google, чтобы сохранить карму и историю на всех устройствах.',
    add_tag_btn: 'ТЕГ',
    tags_placeholder: 'Теги через запятую',
    sort_newest: 'НОВЫЕ',
    sort_oldest: 'СТАРЫЕ',
    sort_best: 'ЛУЧШИЕ',
    sort_newest_short: 'НОВЫЕ',
    sort_oldest_short: 'СТАРЫЕ',
    sort_best_short: 'ТОП',
    popular_tags_label: 'СООБЩЕСТВА',
    preloader_title: 'RETROLOG',
    preloader_subtitle: 'УСТАНОВКА СВЯЗИ',
    next_msg_label: 'СЛЕД.',
    admin_login_title: 'ROOT ДОСТУП',
    login_btn: 'ВОЙТИ',
    logout_btn: 'ВЫЙТИ',
    block_btn: 'БАН',
    admin_badge: 'МОД',
    hide_panel_btn: 'СКРЫТЬ',
    expand_panel_btn: 'ПОКАЗАТЬ',
    menu_btn: 'МЕНЮ',
    close_btn: 'ЗАКРЫТЬ',
    mobile_footer_text_1: 'Next-gen BBS система.',
    mobile_footer_text_2: '2025. Retrolog Network.',
    login_google: 'ВОЙТИ ЧЕРЕЗ GOOGLE',
    guest_mode: 'ГОСТЕВОЙ РЕЖИМ',
    // Auth Modal
    auth_title_login: 'ВХОД В СИСТЕМУ',
    auth_title_register: 'РЕГИСТРАЦИЯ',
    auth_google_btn: 'ПРОДОЛЖИТЬ ЧЕРЕЗ GOOGLE',
    auth_apple_btn: 'ПРОДОЛЖИТЬ ЧЕРЕЗ APPLE',
    auth_or_divider: 'ИЛИ',
    auth_email_label: 'ЭЛ. ПОЧТА',
    auth_password_label: 'ПАРОЛЬ',
    auth_username_label: 'НИКНЕЙМ',
    auth_forgot_pass: 'ЗАБЫЛИ ПАРОЛЬ?',
    auth_has_account: 'УЖЕ ЕСТЬ АККАУНТ?',
    auth_no_account: 'ЕЩЕ НЕТ АККАУНТА?',
    auth_submit_login: 'ВОЙТИ',
    auth_submit_register: 'ПРОДОЛЖИТЬ',
    auth_disclaimer: 'ИНИЦИАЛИЗАЦИЯ СЕССИИ. ПРОДОЛЖАЯ, ВЫ ПОДТВЕРЖДАЕТЕ СОГЛАСИЕ С ПРОТОКОЛОМ 7 (ПРАВИЛА) И ПОЛИТИКОЙ ХРАНЕНИЯ ДАННЫХ.',
    auth_switch_login: 'ВОЙТИ',
    auth_switch_register: 'ЗАРЕГИСТРИРОВАТЬСЯ',
    // Auth Errors
    error_generic: 'ОШИБКА АВТОРИЗАЦИИ',
    error_invalid_email: 'НЕВЕРНЫЙ ФОРМАТ EMAIL',
    error_user_disabled: 'АККАУНТ ОТКЛЮЧЕН',
    error_user_not_found: 'ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН',
    error_wrong_password: 'НЕВЕРНЫЙ ПАРОЛЬ',
    error_email_already_in_use: 'EMAIL УЖЕ ЗАРЕГИСТРИРОВАН',
    error_weak_password: 'ПАРОЛЬ СЛИШКОМ ПРОСТОЙ',
    error_missing_fields: 'ЗАПОЛНИТЕ ВСЕ ПОЛЯ',
    // Auth Success
    auth_reset_sent: 'ССЫЛКА СБРОСА ОТПРАВЛЕНА',
    auth_verification_sent: 'ПИСЬМО ПОДТВЕРЖДЕНИЯ ОТПРАВЛЕНО',
  }
};